version: '3.8'

services:
  facefusion-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    volumes:
      - ./.assets:/facefusion/.assets
      - ./.caches:/facefusion/.caches
      - ./.jobs:/facefusion/.jobs
    ports:
      - "7865:7860"
