FROM python:3.12

ARG FACEFUSION_VERSION=3.1.1
ENV GRADIO_SERVER_NAME=0.0.0.0
ENV PIP_BREAK_SYSTEM_PACKAGES=1

WORKDIR /facefusion

RUN apt-get update && apt-get install -y curl ffmpeg git
RUN git clone https://github.com/singhalishaan/facefusion.git .

# Install dependencies
RUN python install.py --onnxruntime default --skip-conda

# Confirm the presence of process.py
CMD ["python", "process.py"]
